### ISSUE TITLE
bone Name 上 一點印出的問題

### ISSUE THREAD

**Issue by XingSkyrim** [Yu5h1/Skyrim-SMPdocEditor#3]
在最後的" 多印了一格 空白 
舉例:
bone name="HaiSMW_Xing_000" />
bone name="HaiSMW_Xing_100" />
bone name="HaiSMW_Xing_200" />
bone name="HaiSMW_Xing_300" />
bone name="HaiSMW_Xing_400" />
bone name="HaiSMW_Xing_500" />
bone name="HaiSMW_Xing_600" />
bone name="HaiSMW_Xing_700" />

generic-constraint bodyA="VelSM_Xing_100" bodyB="VelSM_Xing_000" />
generic-constraint bodyA="VelSM_Xing_101" bodyB="VelSM_Xing_001" />
generic-constraint bodyA="VelSM_Xing_102" bodyB="VelSM_Xing_002" />

**Comment by Yu5h1** [comment]
是不希望多空白嗎 ? 
那是正常的 ^.<
